apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tienda
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: tienda
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ventas_db;
    CREATE DATABASE IF NOT EXISTS despacho_db;

    USE ventas_db;
    CREATE TABLE IF NOT EXISTS venta (
        id_venta BIGINT AUTO_INCREMENT PRIMARY KEY,
        direccion_compra VARCHAR(255),
        valor_compra INT,
        fecha_compra DATE,
        despacho_generado BOOLEAN DEFAULT FALSE
    );

    INSERT INTO venta (direccion_compra, valor_compra, fecha_compra, despacho_generado) 
    VALUES ('Av. Siempre Viva 742', 15000, '2026-05-14', false), ('Calle Falsa 123', 25000, '2026-05-14', false);

    USE despacho_db;
    CREATE TABLE IF NOT EXISTS despacho (
        id_despacho BIGINT AUTO_INCREMENT PRIMARY KEY,
        id_compra BIGINT,
        direccion_compra VARCHAR(255),
        valor_compra BIGINT,
        fecha_despacho DATE,
        patente_camion VARCHAR(255),
        intento INT DEFAULT 0,
        despachado BOOLEAN DEFAULT FALSE
    );

    INSERT INTO despacho (id_compra, direccion_compra, valor_compra, fecha_despacho, patente_camion, intento, despachado) 
    VALUES (1, 'Av. Siempre Viva 742', 15000, '2026-05-15', 'ABCD-12', 0, false);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-db
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-db
  template:
    metadata:
      labels:
        app: tienda-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-db
  namespace: tienda
spec:
  selector:
    app: tienda-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306